/* ==========================================================================
   KAGURA RESTAURANT - DISH DATA & MENU CATALOG
   ========================================================================== */

const MENU_DATA = [
  {
    id: "kagura-wagyu-a5",
    name: "Kagoshima A5 Wagyu Ribeye",
    nameTh: "เนื้อวากิว คาโกชิมะ A5 ริบอาย",
    category: "steaks",
    price: 2890,
    rating: 4.9,
    reviewsCount: 148,
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
    description: "เนื้อวากิวญี่ปุ่นระดับพรีเมียม A5 นำเข้าจากคาโกชิมะ ย่างด้วยถ่านบินโชตัน เสิร์ฟพร้อมเกลือทรัฟเฟิลและกระเทียมย่าง",
    ingredients: "Japanese A5 Wagyu, Binchotan Charcoal, Black Truffle Salt, Smoked Garlic, Wasabi Relish",
    calories: "680 kcal",
    prepTime: "20-25 นาที",
    spiceLevel: 0,
    tags: ["Signature", "Chef Choice"],
    isFeatured: true
  },
  {
    id: "kagura-tomahawk",
    name: "Dry-Aged Black Angus Tomahawk",
    nameTh: "โทมาฮอว์ก แบล็กแองกัส ดรายเอจ 45 วัน",
    category: "steaks",
    price: 3850,
    rating: 4.8,
    reviewsCount: 92,
    image: "https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80",
    description: "เนื้อโทมาฮอว์กน้ำหนัก 1.2 กิโลกรัม ดรายเอจนาน 45 วัน กลิ่นหอมเข้มข้น รสสัมผัสชุ่มฉ่ำ เสิร์ฟพร้อมซอสแจ่วเบอร์บอนและไวน์แดง",
    ingredients: "Prime Angus Beef 1.2kg, Thyme Butter, Red Wine Glaze, Roasted Bone Marrow",
    calories: "1,250 kcal (แชร์ได้ 2-3 ท่าน)",
    prepTime: "30-35 นาที",
    spiceLevel: 1,
    tags: ["Recommended", "Shareable"],
    isFeatured: true
  },
  {
    id: "kagura-truffle-pasta",
    name: "Fresh Black Truffle Tagliolini",
    nameTh: "พาสต้าเส้นสด ทรัฟเฟิลดำสดจากอิตาลี",
    category: "specials",
    price: 950,
    rating: 4.9,
    reviewsCount: 184,
    image: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?auto=format&fit=crop&w=800&q=80",
    description: "พาสต้าเส้นสดนวดมือทุกเช้า คลุกเคล้าเนยปามาซาน 24 เดือน สไลซ์เห็ดทรัฟเฟิลดำสดส่งตรงจากนอร์ชา อิตาลี",
    ingredients: "Fresh Egg Tagliolini, 24M Parmigiano Reggiano, Fresh Norcia Truffle, Brown Butter",
    calories: "520 kcal",
    prepTime: "15 นาที",
    spiceLevel: 0,
    tags: ["Chef Choice", "Vegetarian"],
    isFeatured: true
  },
  {
    id: "kagura-lobster-tail",
    name: "Grilled Boston Lobster with Garlic Herb",
    nameTh: "ล็อบสเตอร์บอสตันย่างเนยกระเทียมสมุนไพร",
    category: "seafood",
    price: 1890,
    rating: 4.7,
    reviewsCount: 76,
    image: "https://images.unsplash.com/photo-1559737558-245cb3114d59?auto=format&fit=crop&w=800&q=80",
    description: "ล็อบสเตอร์เป็นสด ย่างไฟเปลวถ่านอ่อน ทาเนยเนยกระเทียมโรสแมรี่ เสิร์ฟกับเลมอนเผาและซอสบียาร์เนสส้มยูซุ",
    ingredients: "Live Boston Lobster, Herb Clarified Butter, Yuzu Béarnaise, Charred Lemon",
    calories: "430 kcal",
    prepTime: "18 นาที",
    spiceLevel: 0,
    tags: ["Recommended", "Seafood"],
    isFeatured: true
  },
  {
    id: "kagura-salmon-tartare",
    name: "Norwegian Smoked Salmon Tartare",
    nameTh: "ทาร์ทาร์แซลมอนรมควัน นอร์เวย์",
    category: "starters",
    price: 490,
    rating: 4.6,
    reviewsCount: 110,
    image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
    description: "แซลมอนเกรดซาซิมิคลุกเคล้าอะโวคาโด เคเปอร์ หอมแดง และน้ำสลัดซิตรัสยูซุ เสิร์ฟพร้อมแผ่นข้าวเกรียบหมึกดำกรอบ",
    ingredients: "Sashimi Grade Salmon, Hass Avocado, Capers, Yuzu Vinaigrette, Squid Ink Crisp",
    calories: "320 kcal",
    prepTime: "10 นาที",
    spiceLevel: 0,
    tags: ["Starter", "Healthy"],
    isFeatured: false
  },
  {
    id: "kagura-spicy-beef-salad",
    name: "Flamed Wagyu Spicy Thai Beef Salad",
    nameTh: "ยำเนื้อวากิวสะดุ้งไฟ รสจัดจ้านสูตรคากุระ",
    category: "starters",
    price: 580,
    rating: 4.8,
    reviewsCount: 135,
    image: "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    description: "เนื้อออสเตรเลียนวากิวย่างไฟแรงแบบมีเดียมแรร์ คลุกน้ำยำสมุนไพรสด พริกขี้หนูสวน สะระแหน่ และข้าวคั่วหอมฟุ้ง",
    ingredients: "Australian Wagyu MB5+, Fresh Garden Chillies, Mint, Roasted Rice Powder, Lime Dressing",
    calories: "340 kcal",
    prepTime: "12 นาที",
    spiceLevel: 2,
    tags: ["Spicy", "Recommended"],
    isFeatured: false
  },
  {
    id: "kagura-foie-gras",
    name: "Pan-Seared Foie Gras with Berry Reduction",
    nameTh: "ฟัวกราส์ย่างกระทะ ซอสเบอร์รี่ไวน์แดง",
    category: "starters",
    price: 790,
    rating: 4.9,
    reviewsCount: 88,
    image: "https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80",
    description: "ตับห่านรูจิเยร์จากฝรั่งเศส เซียร์ผิวนอกกรอบสีทอง เนื้อในนุ่มละมุน ราดซอสมัลเบอร์รี่และบริยอชปิ้งเนย",
    ingredients: "French Rougié Foie Gras, Toasted Brioche, Mixed Berry & Port Reduction, Microgreens",
    calories: "480 kcal",
    prepTime: "12 นาที",
    spiceLevel: 0,
    tags: ["Luxury", "Chef Choice"],
    isFeatured: false
  },
  {
    id: "kagura-choc-lava",
    name: "Valrhona Crimson Dark Chocolate Sphere",
    nameTh: "ดาร์กช็อกโกแลตลาวาวัลโรนา & ราสเบอร์รี่สด",
    category: "desserts",
    price: 390,
    rating: 4.9,
    reviewsCount: 220,
    image: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    description: "ดาร์กช็อกโกแลต 70% จากฝรั่งเศส ไส้ลาวาเยิ้มอุ่น เสิร์ฟคู่กับไอศกรีมวานิลลามาดากัสการ์และซอสราสเบอร์รี่สีเลือดหมูสด",
    ingredients: "70% Valrhona Guanaja, Bourbon Vanilla Gelato, Fresh Raspberries, Gold Leaf",
    calories: "460 kcal",
    prepTime: "15 นาที",
    spiceLevel: 0,
    tags: ["Recommended", "Dessert"],
    isFeatured: true
  },
  {
    id: "kagura-basque-cheesecake",
    name: "Smoked Basque Burnt Cheesecake",
    nameTh: "ชีสเค้กหน้าไหม้รมควันไม้โอ๊ค",
    category: "desserts",
    price: 320,
    rating: 4.8,
    reviewsCount: 165,
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?auto=format&fit=crop&w=800&q=80",
    description: "ชีสเค้กสไตล์บาสก์อบเตาถ่านหน้าไหม้หอมกรุ่น เนื้อในเยิ้มเนียนนุ่ม หวานน้อยกลมกล่อม",
    ingredients: "Cream Cheese, Organic Eggs, Pure Cream, Madagascar Vanilla, Oak Smoke Infusion",
    calories: "390 kcal",
    prepTime: "พร้อมเสิร์ฟ",
    spiceLevel: 0,
    tags: ["Dessert", "Best Seller"],
    isFeatured: false
  },
  {
    id: "kagura-crimson-cocktail",
    name: "Blood Moon Smoked Negroni",
    nameTh: "บลัดมูน สโมค เนโกรนี (Signature Drink)",
    category: "drinks",
    price: 450,
    rating: 4.9,
    reviewsCount: 142,
    image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=800&q=80",
    description: "ค็อกเทลสีทับทิมเข้มข้น ผสมผสาน Campari, Sweet Vermouth, Dry Gin รมควันกิ่งโรสแมรี่สดในโดมแก้ว",
    ingredients: "Craft Gin, Campari, Antica Formula, Smoked Rosemary, Flamed Orange Peel",
    calories: "190 kcal",
    prepTime: "5 นาที",
    spiceLevel: 0,
    tags: ["Cocktail", "Signature"],
    isFeatured: true
  },
  {
    id: "kagura-ruby-mocktail",
    name: "Ruby Rose Sparkling Elixir (Non-Alcohol)",
    nameTh: "รูบี้โรส สปาร์กลิ้ง ม็อกเทล (ไร้แอลกอฮอล์)",
    category: "drinks",
    price: 260,
    rating: 4.7,
    reviewsCount: 89,
    image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80",
    description: "น้ำผลไม้ทับทิมแท้สกัดเย็น ผสานกลิ่นกุหลาบดามาสค์ ส้มยูซุ และโซดาระดับพรีเมียม สดชื่นหรูหรา",
    ingredients: "Pomegranate Reduction, Damask Rose Mist, Fresh Yuzu Juice, Craft Sparkling Soda",
    calories: "110 kcal",
    prepTime: "5 นาที",
    spiceLevel: 0,
    tags: ["Mocktail", "Refreshing"],
    isFeatured: false
  }
];

// Table Seating Zones for Reservation
const SEATING_ZONES = [
  {
    id: "vip-lounge",
    name: "The Crimson VIP Lounge",
    nameTh: "ห้องวีไอพี เลานจ์ส่วนตัว",
    capacity: "4 - 12 ท่าน",
    surcharge: "ขั้นต่ำ 5,000฿",
    description: "ห้องส่วนตัวระดับเอ็กซ์คลูซีฟ พร้อมบัตเลอร์ส่วนตัวและระบบเสียง Hi-Fi สำหรับการเจรจาธุรกิจหรืองานฉลองคนพิเศษ",
    badge: "Exclusive",
    image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "chef-counter",
    name: "Chef's Flame Counter",
    nameTh: "เคาน์เตอร์หน้าเตาไฟเชฟ",
    capacity: "1 - 4 ท่าน",
    surcharge: "ไม่มีค่าบริการเพิ่ม",
    description: "สัมผัสประสบการณ์ใกล้ชิดหน้าเตาย่างถ่านบินโชตัน ชมศิลปะการแล่เนื้อและเซียร์ไฟสดๆ จากหัวหน้าเชฟ",
    badge: "Most Popular",
    image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "romantic-terrace",
    name: "Starry Sky Terrace",
    nameTh: "ระเบียงชมดาวโรแมนติก",
    capacity: "2 ท่าน (โต๊ะคู่)",
    surcharge: "ไม่มีค่าบริการเพิ่ม",
    description: "โต๊ะรับลมชมวิวเมืองยามค่ำคืนใต้แสงดาว แสงเทียนสลัว เหมาะที่สุดสำหรับเดตโรแมนติกและวันครบรอบ",
    badge: "Romantic",
    image: "https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?auto=format&fit=crop&w=800&q=80"
  },
  {
    id: "main-dining",
    name: "Grand Dining Hall",
    nameTh: "โถงรับประทานอาหารหลัก",
    capacity: "2 - 8 ท่าน",
    surcharge: "ไม่มีค่าบริการเพิ่ม",
    description: "บรรยากาศห้องอาหารหรูหราโทนสีดำ-แดง ตกแต่งด้วยโคมไฟระย้าดีไซน์โมเดิร์น โต๊ะกว้างขวางนั่งสบาย",
    badge: "Standard",
    image: "https://images.unsplash.com/photo-1551632436-cbf8dd35adfa?auto=format&fit=crop&w=800&q=80"
  }
];
